import { Role } from './constants';

export const PERMISSIONS = {
  // Navigation & Page Access
  VIEW_USERS: [Role.ADMIN],
  MANAGE_USERS: [Role.ADMIN],

  VIEW_DEPARTMENTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_DEPARTMENTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_ALL_EMPLOYEES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_EMPLOYEES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_CONTRACTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_CONTRACTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_SCHEDULES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_SCHEDULES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_ALL_ATTENDANCE: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_ATTENDANCE: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANUAL_ATTENDANCE_CORRECTION: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_TIME_OFF_TYPES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER, Role.EMPLOYEE],
  MANAGE_TIME_OFF_TYPES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_ALLOCATIONS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER, Role.EMPLOYEE],
  MANAGE_ALLOCATIONS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_TIME_OFF_REQUESTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER, Role.EMPLOYEE],
  APPROVE_TIME_OFF: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  // Payroll Permissions
  VIEW_SALARY_STRUCTURES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_SALARY_STRUCTURES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_SALARY_RULES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_SALARY_RULES: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_PAYRUNS: [Role.ADMIN, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  CREATE_PAYRUN: [Role.ADMIN, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  COMPUTE_PAYRUN: [Role.ADMIN, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  VALIDATE_PAYRUN: [Role.ADMIN, Role.HR_PAYROLL_MANAGER],
  MARK_PAID_PAYRUN: [Role.ADMIN, Role.HR_PAYROLL_MANAGER],
  DELETE_PAYRUN: [Role.ADMIN, Role.HR_PAYROLL_MANAGER],
  SEND_PAYSLIPS: [Role.ADMIN, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],

  VIEW_PAYSLIPS: [Role.ADMIN, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER, Role.EMPLOYEE],

  VIEW_DASHBOARD: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER, Role.EMPLOYEE],

  // Attendance Alert Permissions
  VIEW_ATTENDANCE_ALERTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
  MANAGE_ATTENDANCE_ALERTS: [Role.ADMIN, Role.HR_MANAGER, Role.HR_PAYROLL_USER, Role.HR_PAYROLL_MANAGER],
};

export function hasPermission(userRole, permissionKey) {
  if (!userRole) return false;
  const allowedRoles = PERMISSIONS[permissionKey];
  if (!allowedRoles) return false;
  return allowedRoles.includes(userRole);
}

export function isEmployeeOnly(userRole) {
  return userRole === Role.EMPLOYEE;
}
